# Generated by Django 3.1.14 on 2022-04-24 22:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('main', '0003_auto_20220424_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_white', models.ImageField(upload_to='logo_white', verbose_name='logo para fondos oscuros')),
                ('logo_black', models.ImageField(upload_to='logo_black', verbose_name='logo para fondos oscuros')),
                ('contact_center_detail', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Descripción sección contact center')),
                ('footer_detail', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Descripción sección pie de página')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configuraciones de la página',
                'verbose_name_plural': 'Configuraciones de la página',
            },
        ),
    ]
