# Generated by Django 3.1.14 on 2022-04-24 23:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='address',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Dirección(es) de ubicación'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='email',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Correo(s) de contacto'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='phone_number',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Número(s) de contacto'),
        ),
    ]
