# Generated by Django 3.1.14 on 2022-04-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carousel_client_new_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='icon_black',
            field=models.ImageField(blank=True, upload_to='socialnetwork', verbose_name='Icono en negro'),
        ),
    ]
