# Generated by Django 3.1.14 on 2022-04-25 03:44

from django.db import migrations, models
import django.db.models.manager
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220424_2352'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='pagesettings',
            name='contact_center_detail',
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='contact_detail',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Descripción sección contactanos'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='icon_white',
            field=models.ImageField(blank=True, upload_to='socialnetwork', verbose_name='Icono en blanco'),
        ),
        migrations.AlterField(
            model_name='service',
            name='preview_in_home',
            field=models.BooleanField(default=True, verbose_name='visualizar en el carrousel de servicios del inicio'),
        ),
    ]
