# Generated by Django 3.1.14 on 2022-04-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220425_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Imagen del carousel principal', 'verbose_name_plural': 'Imágenes del carousel principal'},
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='title',
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='bottom_trust_phrase',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='renglón inferior de la frase de confianza'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='top_trust_phrase',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='renglón superior de la frase de confianza'),
        ),
    ]
