# Generated by Django 3.1.14 on 2022-04-25 06:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_auto_20220425_0441"),
    ]

    operations = [
        migrations.AddField(
            model_name="new",
            name="slug",
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from="title"),
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from="name"),
        ),
    ]
