# Generated by Django 3.1.14 on 2022-04-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_menu_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='menu', verbose_name='icono'),
        ),
    ]
