# Generated by Django 3.1.14 on 2022-05-14 01:33

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_menuitem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailindexpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AddField(
            model_name='detailindexpage',
            name='content_title',
            field=models.CharField(default='sdsd', max_length=150, verbose_name='titulo del contenido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailindexpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages', verbose_name='imagen'),
        ),
    ]
