# Generated by Django 3.1.14 on 2022-08-03 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20220514_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='bottom_trust_phrase',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='renglón inferior de la frase de confianza'),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='top_trust_phrase',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='renglón superior de la frase de confianza'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('icon', models.ImageField(blank=True, upload_to='payment', verbose_name='icono del medio de pago')),
                ('link', models.URLField(verbose_name='link del medio de pago')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pagos',
            },
        ),
    ]
