# Generated by Django 3.1.14 on 2022-04-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='sort_order',
        ),
    ]
