# Generated by Django 3.1.14 on 2022-04-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_remove_voucher_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor de la transacción'),
        ),
    ]
