# Generated by Django 3.1.14 on 2022-04-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_auto_20220424_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='voucher',
            name='successful_payment',
            field=models.BooleanField(default=False, verbose_name='El pago se realizó correctamente'),
        ),
    ]
