# Generated by Django 3.1.14 on 2022-04-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_auto_20220427_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electronico'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='numero telefónico'),
        ),
    ]
