# Generated by Django 3.1.14 on 2022-04-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_auto_20220427_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='epayco_transaction_detail',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='descripción de la transacción de epayco'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='epayco_response',
            field=models.JSONField(null=True, verbose_name='respuesta detallada de epayco'),
        ),
    ]
