# Generated by Django 3.1.14 on 2022-04-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_auto_20220427_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='epayco_transaction_detail',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='descripción de la transacción de epayco'),
        ),
    ]
