# Generated by Django 3.1.14 on 2022-05-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0003_searchresultspage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResultsPage',
        ),
    ]
