# Generated by Django 3.1.14 on 2022-04-25 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres y apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo(s) de contacto')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Número(s) de contacto')),
                ('subject', wagtail.core.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Asunto')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Formulario de contacto',
                'verbose_name_plural': 'Formularios de contactos',
            },
        ),
    ]
