# Generated by Django 3.1.14 on 2022-04-27 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo')),
                ('name_applicant', models.CharField(max_length=100, verbose_name='Nombre del aplicante')),
                ('email_applicant', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo(s) de contacto del aplicante')),
                ('phone_number_applicant', models.CharField(blank=True, max_length=20, verbose_name='Número(s) de contacto del aplicante')),
                ('subject_applicant', wagtail.core.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Asunto')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Bolsa de empleo',
                'verbose_name_plural': 'Bolsa de empleos',
            },
        ),
    ]
