# Generated by Django 3.1.14 on 2022-04-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to='Files/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='job',
            name='email_applicant',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo(s) de contacto del aplicante'),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone_number_applicant',
            field=models.CharField(max_length=20, verbose_name='Número(s) de contacto del aplicante'),
        ),
        migrations.AlterField(
            model_name='job',
            name='subject_applicant',
            field=models.TextField(max_length=200, null=True, verbose_name='Asunto'),
        ),
    ]
